// Add these tools to reach 200+

const moreTools = [
  // === MORE UK STOCK BROKERS ===
  {
    id: 79, name: "Trading 212", slug: "trading-212", logo: "T2",
    rating: null,
    description: "UK's popular commission-free investing app with ISA accounts.",
    longDescription: "Trading 212 is a UK-based commission-free investing platform founded in 2006, offering stocks, ETFs, and CFDs with zero commission. Known for its user-friendly app and innovative AutoInvest feature.",
    category: "Stock Brokers", categoryId: 3,
    features: ["0% Commission", "Stocks & ETFs", "ISA Account", "AutoInvest", "CFD Trading"],
    pros: ["Zero commission trading", "User-friendly app", "ISA tax benefits", "AutoInvest feature", "Fractional shares"],
    cons: ["Not FCA protected for CFDs", "Limited research", "Currency conversion fees", "No phone support"],
    pricing: "0% Commission", pricingDetail: "Stocks/ETFs: 0%. CFDs: Spread only. Currency conversion: 0.15%. Overnight fees for CFDs.",
    minDeposit: "$1", platforms: ["iOS", "Android", "Web"],
    website: "https://trading212.com", affiliate: false, trending: true, featured: true,
    yearFounded: 2006, regulation: ["FCA", "CySEC"],
    supportedCountries: ["UK", "EU", "Global"],
    depositMethods: ["Bank Transfer", "Card", "PayPal"],
    withdrawalTime: "1-3 business days",
    customerSupport: "Email, Chat",
    mobileApp: true, demoAccount: true,
    bestFor: ["UK Investors", "ISA Seekers", "Beginner Investors"],
    faq: [{ q: "Is Trading 212 safe?", a: "Yes, Trading 212 is FCA regulated with FSCS protection up to £85,000 for UK clients." }],
  },
  {
    id: 80, name: "Hargreaves Lansdown", slug: "hargreaves-lansdown", logo: "HL",
    rating: null,
    description: "UK's largest investment platform with full-service brokerage.",
    longDescription: "Hargreaves Lansdown is the UK's largest investment platform, founded in 1981, serving over 1.5 million investors with comprehensive investment services including shares, funds, pensions, and ISAs.",
    category: "Stock Brokers", categoryId: 3,
    features: ["Full-Service Broker", "Pension & ISA", "Fund Supermarket", "Research Tools", "Wealth Management"],
    pros: ["Largest UK platform", "Comprehensive services", "Excellent research", "FSCS protected", "Award-winning"],
    cons: ["Higher fees than discounters", "No zero-commission", "Complex fee structure", "US stocks expensive"],
    pricing: "0.45% annual + dealing fees", pricingDetail: "Shares: £11.95/trade. Funds: 0.45%/year (capped). ISA: £11.95/year.",
    minDeposit: "$0", platforms: ["Web", "iOS", "Android"],
    website: "https://hl.co.uk", affiliate: false, trending: false, featured: false,
    yearFounded: 1981, regulation: ["FCA", "FSCS"],
    supportedCountries: ["United Kingdom"],
    depositMethods: ["Bank Transfer", "Cheque"],
    withdrawalTime: "3-5 business days",
    customerSupport: "Phone, Email, Website",
    mobileApp: true, demoAccount: false,
    bestFor: ["UK Long-term Investors", "Pension Savers", "Fund Investors"],
    faq: [{ q: "Is HL safe?", a: "Yes, Hargreaves Lansdown is FCA regulated with FSCS protection up to £85,000." }],
  },
  {
    id: 81, name: "Interactive Investor", slug: "interactive-investor", logo: "II",
    rating: null,
    description: "UK flat-fee investment platform with pension and ISA.",
    longDescription: "Interactive Investor is a UK investment platform founded in 1995, known for flat-fee pricing rather than percentage-based fees, making it cost-effective for larger portfolios.",
    category: "Stock Brokers", categoryId: 3,
    features: ["Flat-Fee Pricing", "ISA & Pension", "Investment Trusts", "Trading Tools", "Research"],
    pros: ["Flat fees (better for large portfolios)", "Wide fund selection", "Good research", "FSCS protected", "UK-focused"],
    cons: ["Monthly fee (£9.99)", "Not suitable for small portfolios", "Higher dealing charges", "Basic app"],
    pricing: "£9.99/month + £3.99/trade", pricingDetail: "Monthly: £9.99. Trades: £3.99. Funds: Included. ISA/Pension: Included.",
    minDeposit: "$0", platforms: ["Web", "iOS", "Android"],
    website: "https://interactiveinvestor.co.uk", affiliate: false, trending: false, featured: false,
    yearFounded: 1995, regulation: ["FCA", "FSCS"],
    supportedCountries: ["United Kingdom"],
    depositMethods: ["Bank Transfer", "Direct Debit"],
    withdrawalTime: "3-5 business days",
    customerSupport: "Phone, Email",
    mobileApp: true, demoAccount: false,
    bestFor: ["UK Large Portfolios", "Flat-Fee Seekers", "Fund Investors"],
    faq: [{ q: "When is ii worth it?", a: "Interactive Investor is cost-effective for portfolios over £25,000 due to flat fees." }],
  },
  
  // === MORE US STOCK BROKERS ===
  {
    id: 82, name: "Vanguard", slug: "vanguard", logo: "VG",
    rating: null,
    description: "Index fund pioneer with low-cost investing for long-term investors.",
    longDescription: "Vanguard is an investment management company founded in 1975, known for pioneering index funds and ultra-low-cost investing. With $7+ trillion in assets, Vanguard is owned by its funds, meaning clients own Vanguard.",
    category: "Stock Brokers", categoryId: 3,
    features: ["Index Fund Pioneer", "$0 Commission", "Low Expense Ratios", "Retirement Accounts", "Target-Date Funds"],
    pros: ["Ultra-low expense ratios", "Client-owned structure", "Excellent index funds", "Long-term focus", "Trusted brand"],
    cons: ["Basic trading platform", "Limited active trading tools", "No crypto", "Conservative approach"],
    pricing: "$0 stock trades", pricingDetail: "Stocks/ETFs: $0. Vanguard funds: No transaction fee. Non-Vanguard funds: $20.",
    minDeposit: "$0", platforms: ["Web", "iOS", "Android"],
    website: "https://investor.vanguard.com", affiliate: false, trending: false, featured: true,
    yearFounded: 1975, regulation: ["SEC", "FINRA", "SIPC"],
    supportedCountries: ["United States", "UK", "Australia", "Canada"],
    depositMethods: ["ACH", "Wire Transfer", "Check"],
    withdrawalTime: "1-3 business days",
    customerSupport: "Phone, Email",
    mobileApp: true, demoAccount: false,
    bestFor: ["Long-term Investors", "Index Fund Investors", "Retirement Savers"],
    faq: [{ q: "Who owns Vanguard?", a: "Vanguard is owned by its funds, meaning the investors own Vanguard itself." }],
  },
  {
    id: 83, name: "Betterment", slug: "betterment", logo: "BT",
    rating: null,
    description: "Robo-advisor with automated investing and tax-loss harvesting.",
    longDescription: "Betterment is the largest independent robo-advisor, founded in 2008, offering automated investing with tax-loss harvesting, goal-based planning, and low fees.",
    category: "Stock Brokers", categoryId: 3,
    features: ["Robo-Advisor", "Tax-Loss Harvesting", "Goal Planning", "Automatic Rebalancing", "Socially Responsible Portfolios"],
    pros: ["Hands-off investing", "Tax-loss harvesting", "Goal-based planning", "Low fees (0.25%)", "Automatic rebalancing"],
    cons: ["No individual stock picking", "Limited customization", "Only ETFs", "Premium tier expensive"],
    pricing: "0.25% annual", pricingDetail: "Digital: 0.25%/year. Premium: 0.40%/year (min $100K). No trading commissions.",
    minDeposit: "$0", platforms: ["Web", "iOS", "Android"],
    website: "https://betterment.com", affiliate: false, trending: true, featured: false,
    yearFounded: 2008, regulation: ["SEC", "SIPC"],
    supportedCountries: ["United States"],
    depositMethods: ["ACH", "Wire Transfer"],
    withdrawalTime: "2-3 business days",
    customerSupport: "Email, Phone (Premium)",
    mobileApp: true, demoAccount: false,
    bestFor: ["Passive Investors", "Automated Investing", "Tax Optimization"],
    faq: [{ q: "Is Betterment worth it?", a: "Yes, for hands-off investors. 0.25% fee includes tax-loss harvesting and automatic rebalancing." }],
  },
  {
    id: 84, name: "Wealthfront", slug: "wealthfront", logo: "WF",
    rating: null,
    description: "Robo-advisor with advanced tax strategies and 529 plans.",
    longDescription: "Wealthfront is a leading robo-advisor founded in 2008, offering automated investing with advanced tax strategies including tax-loss harvesting, direct indexing, and 529 college savings plans.",
    category: "Stock Brokers", categoryId: 3,
    features: ["Robo-Advisor", "Tax-Loss Harvesting", "Direct Indexing", "529 Plans", "Cash Account"],
    pros: ["Advanced tax strategies", "Direct indexing", "529 plans available", "Competitive fees", "High-yield cash account"],
    cons: ["No human advisors", "Limited customization", "Only ETFs", "US clients only"],
    pricing: "0.25% annual", pricingDetail: "First $5K managed free. Then 0.25%/year. Direct indexing: Included over $100K.",
    minDeposit: "$500", platforms: ["Web", "iOS", "Android"],
    website: "https://wealthfront.com", affiliate: false, trending: false, featured: false,
    yearFounded: 2008, regulation: ["SEC", "SIPC"],
    supportedCountries: ["United States"],
    depositMethods: ["ACH", "Wire Transfer"],
    withdrawalTime: "2-3 business days",
    customerSupport: "Email, Help Center",
    mobileApp: true, demoAccount: false,
    bestFor: ["Tax-Conscious Investors", "College Savings", "Automated Investing"],
    faq: [{ q: "Is Wealthfront safe?", a: "Yes, Wealthfront is SEC-registered with SIPC protection up to $500,000." }],
  },
  
  // === MORE EU BROKERS ===
  {
    id: 85, name: "Binance", slug: "binance-eu", logo: "BN",
    rating: null,
    description: "World's largest crypto exchange with EU compliance.",
    longDescription: "Binance is the world's largest cryptocurrency exchange by volume, with dedicated EU operations complying with European regulations including MiCA.",
    category: "Crypto Exchanges", categoryId: 2,
    features: ["100+ Cryptos", "Low Fees", "Staking", "NFT Marketplace", "EU Compliant"],
    pros: ["Largest exchange", "Low fees (0.1%)", "Extensive coin selection", "Staking rewards", "EU regulated entity"],
    cons: ["Regulatory scrutiny", "Complex interface", "Not available in all EU countries", "Customer support"],
    pricing: "0.1% spot trading", pricingDetail: "Spot: 0.1% (0.075% with BNB). Futures: 0.02%/0.04%. Staking: Variable APY.",
    minDeposit: "$10", platforms: ["Web", "iOS", "Android", "Desktop"],
    website: "https://binance.com", affiliate: false, trending: true, featured: true,
    yearFounded: 2017, regulation: ["VARA", "AMF", "Various EU"],
    supportedCountries: ["EU", "Global (excl. restrictions)"],
    depositMethods: ["SEPA", "Card", "P2P", "Crypto"],
    withdrawalTime: "Instant to 24 hours",
    customerSupport: "24/7 Live Chat, Email",
    mobileApp: true, demoAccount: false,
    bestFor: ["EU Crypto Traders", "Low Fees", "Altcoin Trading"],
    faq: [{ q: "Is Binance available in EU?", a: "Yes, Binance operates in EU with local compliance including MiCA regulations." }],
  },
  {
    id: 86, name: "Kraken", slug: "kraken-eu", logo: "KR",
    rating: null,
    description: "Secure US crypto exchange with strong EU presence.",
    longDescription: "Kraken is a US-based cryptocurrency exchange founded in 2011, known for security and compliance, with strong operations in the EU including banking services.",
    category: "Crypto Exchanges", categoryId: 2,
    features: ["Strong Security", "Banking Services", "Staking", "Futures Trading", "OTC Desk"],
    pros: ["Never hacked", "EU banking license", "Competitive fees", "Good liquidity", "Strong compliance"],
    cons: ["Limited altcoins vs Binance", "Complex verification", "Higher fees on simple buy", "US headquarters"],
    pricing: "0.16% maker / 0.26% taker", pricingDetail: "Spot: 0.16%/0.26%. Pro: Lower fees. Staking: 3-15% APY.",
    minDeposit: "$1", platforms: ["Web", "iOS", "Android", "Pro"],
    website: "https://kraken.com", affiliate: false, trending: false, featured: false,
    yearFounded: 2011, regulation: ["FinCEN", "FCA", "BaFin", "Various EU"],
    supportedCountries: ["US", "EU", "Global"],
    depositMethods: ["SEPA", "Bank Transfer", "Card", "Crypto"],
    withdrawalTime: "Instant to 2 days",
    customerSupport: "24/7 Live Chat, Email, Phone",
    mobileApp: true, demoAccount: false,
    bestFor: ["Security-Conscious", "EU Banking", "Serious Traders"],
    faq: [{ q: "Is Kraken safe?", a: "Yes, Kraken has never been hacked and uses industry-leading security measures." }],
  },
  {
    id: 87, name: "Bitstamp", slug: "bitstamp", logo: "BS",
    rating: null,
    description: "Longest-running crypto exchange (2011) with EU base.",
    longDescription: "Bitstamp is the longest-running cryptocurrency exchange, founded in 2011 and based in Luxembourg, offering a secure and compliant platform for European traders.",
    category: "Crypto Exchanges", categoryId: 2,
    features: ["Since 2011", "EU Regulated", "Banking Integration", "Institutional Services", "Staking"],
    pros: ["Oldest exchange", "EU-based (Luxembourg)", "Strong security", "Banking partnerships", "Institutional services"],
    cons: ["Limited coins (~50)", "Higher fees than competitors", "Basic features", "Slower innovation"],
    pricing: "0.25-0.50%", pricingDetail: "Maker: 0.25%. Taker: 0.50%. Volume discounts available. Instant buy: 2%.",
    minDeposit: "$25", platforms: ["Web", "iOS", "Android"],
    website: "https://bitstamp.net", affiliate: false, trending: false, featured: false,
    yearFounded: 2011, regulation: ["CSSF (Luxembourg)", "FinCEN", "FCA"],
    supportedCountries: ["EU", "US", "Global"],
    depositMethods: ["SEPA", "Bank Transfer", "Card", "Crypto"],
    withdrawalTime: "Instant to 3 days",
    customerSupport: "24/7 Live Chat, Email, Phone",
    mobileApp: true, demoAccount: false,
    bestFor: ["EU Traders", "Security-Focused", "Long-term Holders"],
    faq: [{ q: "Is Bitstamp legit?", a: "Yes, Bitstamp is the longest-running exchange (2011) with full EU regulation." }],
  },
  
  // === MORE GLOBAL CRYPTO ===
  {
    id: 88, name: "KuCoin", slug: "kucoin", logo: "KC",
    rating: null,
    description: "Global crypto exchange with 700+ altcoins and low fees.",
    longDescription: "KuCoin is a global cryptocurrency exchange founded in 2017, known for listing new altcoins early and offering one of the largest selections of cryptocurrencies with competitive fees.",
    category: "Crypto Exchanges", categoryId: 2,
    features: ["700+ Cryptos", "Low Fees", "Futures Trading", "Lending", "Trading Bots"],
    pros: ["Largest coin selection", "Low fees (0.1%)", "Early altcoin listings", "Trading bots", "Staking rewards"],
    cons: ["Not regulated in major jurisdictions", "No fiat in many countries", "Customer support issues", "Complex interface"],
    pricing: "0.1% maker/taker", pricingDetail: "Spot: 0.1% (0.08% with KCS). Futures: 0.02%/0.06%. Staking: Variable.",
    minDeposit: "$5", platforms: ["Web", "iOS", "Android"],
    website: "https://kucoin.com", affiliate: false, trending: true, featured: false,
    yearFounded: 2017, regulation: ["MSB (US)", "Various"],
    supportedCountries: ["Global (200+ countries)"],
    depositMethods: ["Crypto", "Card (limited)", "P2P"],
    withdrawalTime: "Instant to 24 hours",
    customerSupport: "24/7 Live Chat, Email",
    mobileApp: true, demoAccount: false,
    bestFor: ["Altcoin Hunters", "Low Fees", "Global Traders"],
    faq: [{ q: "Is KuCoin safe?", a: "KuCoin uses industry security measures but suffered a $280M hack in 2020 (fully reimbursed)." }],
  },
  {
    id: 89, name: "Bybit", slug: "bybit", logo: "BY",
    rating: null,
    description: "Derivatives-focused crypto exchange with low fees and high leverage.",
    longDescription: "Bybit is a cryptocurrency derivatives exchange founded in 2018, known for perpetual contracts with up to 100x leverage and competitive trading fees.",
    category: "Crypto Exchanges", categoryId: 2,
    features: ["Perpetual Contracts", "100x Leverage", "Low Fees", "Copy Trading", "NFT Marketplace"],
    pros: ["Low derivatives fees", "High leverage", "Excellent liquidity", "Copy trading", "No KYC for crypto"],
    cons: ["Not available in US", "Derivatives focus", "Regulatory uncertainty", "Complex for beginners"],
    pricing: "0.1% spot / 0.01-0.06% futures", pricingDetail: "Spot: 0.1%. Futures: 0.01% maker / 0.06% taker.",
    minDeposit: "$0", platforms: ["Web", "iOS", "Android"],
    website: "https://bybit.com", affiliate: false, trending: true, featured: false,
    yearFounded: 2018, regulation: ["VARA", "Various"],
    supportedCountries: ["Global (excl. US, China)"],
    depositMethods: ["Crypto", "Card", "P2P", "Bank Transfer"],
    withdrawalTime: "Instant to 24 hours",
    customerSupport: "24/7 Live Chat, Email",
    mobileApp: true, demoAccount: true,
    bestFor: ["Derivatives Traders", "High Leverage", "Active Crypto"],
    faq: [{ q: "Does Bybit require KYC?", a: "Basic crypto trading doesn't require KYC. Fiat services and higher limits need verification." }],
  },
  {
    id: 90, name: "Gate.io", slug: "gate-io", logo: "GT",
    rating: null,
    description: "Crypto exchange with 1400+ coins and venture capital.",
    longDescription: "Gate.io is a cryptocurrency exchange founded in 2013, offering one of the largest selections of cryptocurrencies (1400+) with venture capital backing for new projects.",
    category: "Crypto Exchanges", categoryId: 2,
    features: ["1400+ Cryptos", "Startup Funding", "Copy Trading", "Lending", "NFT"],
    pros: ["Largest coin selection", "Startup investments", "Copy trading", "Competitive fees", "Long track record"],
    cons: ["Complex interface", "Regulatory concerns", "Customer support", "Limited fiat options"],
    pricing: "0.2% maker/taker", pricingDetail: "Spot: 0.2% (discounts with GT token). Futures: 0.02%/0.04%.",
    minDeposit: "$0", platforms: ["Web", "iOS", "Android"],
    website: "https://gate.io", affiliate: false, trending: false, featured: false,
    yearFounded: 2013, regulation: ["MSB (US)", "Various"],
    supportedCountries: ["Global (100+ countries)"],
    depositMethods: ["Crypto", "Card", "P2P"],
    withdrawalTime: "Instant to 24 hours",
    customerSupport: "24/7 Live Chat, Email",
    mobileApp: true, demoAccount: false,
    bestFor: ["Altcoin Hunters", "Early Projects", "Global Traders"],
    faq: [{ q: "Is Gate.io legit?", a: "Yes, Gate.io has operated since 2013 with millions of users, though regulatory status varies." }],
  },
]

